wip (#541)
Related to
https://github.com/jenkins-infra/helpdesk/issues/3827#issuecomment-1840264684

- Trick Terraform into thinking the AKS `publick8s`'s default node pool
is `systempool3` created in
https://github.com/jenkins-infra/azure/pull/537
- Note that that since
https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.47.0,
we have to specify the `only_critical_addons_enabled` attribute of the
`default_node_pool` block to configure the taint
`"CriticalAddonsOnly=true:NoSchedule"`
- We had to remove/reimport the clutser from state otherwise we were
receiving the following error during apply:

  ```
Error: expanding default_node_pool: The AKS API has removed support for
tainting all nodes in the default node pool and it is no longer possible
to configure this. To taint a node pool, create a separate one.
  ```

- To ease future operations, we decoupled the provider from the AKS
resource by using a data source acting as intermediate

---------

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
Co-authored-by: Damien Duportal <damien.duportal@gmail.com>