feat(trusted.ci.jenkins.io) allow the new sponsored VM to manage the DNS zone (#1439)
Ref.
https://github.com/jenkins-infra/helpdesk/issues/5084#issuecomment-4343922083

This PR allows the new controller-sponsored.trusted.ci.jenkins.io VM to
manage the DNS zone for `trusted.ci.jenkins.io` to allow `certbot` to
request certificates using DNS validation.

It introduces a change in the `azure-letsencrypt-dns` module to allow
passing a list of `principal_id`s instead of only one.
The change adds a set of `moved` block to manage transparently the
existing VM permissions (3 for cert.ci and 3 for trusted.ci).

As such, the new VM adds 3 new permissions.

It should solve the current `certbot` error when calling the `certonly`
subcommand during the Puppet initial bootstrap:

```
2026-05-02 07:44:33,281:DEBUG:certbot_dns_multi._internal.dns_multi:Cleanup error was
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/auth_handler.py", line 84, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.10/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 97, in perform
    LegoClient.present(
  File "/usr/local/lib/python3.10/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 169, in present
    LegoClient._raise_for_response(
  File "/usr/local/lib/python3.10/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 201, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: azuredns: could not find zone (from discovery): trusted.ci.jenkins.io
```

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>