restore kubernetes provider to be able to delete resources
Error: Provider configuration not present
To work with kubernetes_namespace.infracijenkinsio_agents_2_infra_ci_jenkins_io_agents
(orphan) its original provider configuration at
provider["registry.terraform.io/hashicorp/kubernetes"].infracijenkinsio_agents_2
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist
in the state. Re-add the provider configuration to destroy
kubernetes_namespace.infracijenkinsio_agents_2_infra_ci_jenkins_io_agents
(orphan), after which you can remove the provider configuration again.